/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Service = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
export const EventId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : EventId,
  'title' : IDL.Text,
  'createdAt' : Time,
  'pricePerPerson' : IDL.Nat,
  'amountPaid' : IDL.Nat,
  'lastModified' : Time,
  'attendees' : IDL.Nat,
  'dateTimestamp' : Time,
  'services' : IDL.Vec(Service),
  'flatFee' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEvent' : IDL.Func(
      [
        IDL.Text,
        Time,
        IDL.Vec(Service),
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Nat,
      ],
      [EventId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEvent' : IDL.Func([EventId], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([EventId], [Event], ['query']),
  'getEventsByDateRange' : IDL.Func([Time, Time], [IDL.Vec(Event)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEvent' : IDL.Func(
      [
        EventId,
        IDL.Text,
        Time,
        IDL.Vec(Service),
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Service = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
  const EventId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : EventId,
    'title' : IDL.Text,
    'createdAt' : Time,
    'pricePerPerson' : IDL.Nat,
    'amountPaid' : IDL.Nat,
    'lastModified' : Time,
    'attendees' : IDL.Nat,
    'dateTimestamp' : Time,
    'services' : IDL.Vec(Service),
    'flatFee' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEvent' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Vec(Service),
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Nat,
        ],
        [EventId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEvent' : IDL.Func([EventId], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([EventId], [Event], ['query']),
    'getEventsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEvent' : IDL.Func(
        [
          EventId,
          IDL.Text,
          Time,
          IDL.Vec(Service),
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };